# Copyright (c) 02.10.2023 Thomas Zierer.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v20.html
#
# Contributors:
#    Thomas Zierer - initial API and implementation and/or initial documentation

name: Java CI with Maven

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'
    
    - name: Build with Maven
      env:
        nvdApiKey: ${{ secrets.NVDAPIKEY }}
      run: mvn -B verify -Podc,materialize --file pom.xml
      
    - name: Publish package
      if: github.ref == 'refs/heads/main'
      run: |
        mkdir staging 
        cp de.tgmz.eclipse.product/target/products/*.zip staging 
    
    - uses: actions/upload-artifact@v4
      if: github.ref == 'refs/heads/main'
      with:
        name: Package
        path: staging      

    - name: Publish reports
      run: |
        mkdir reports 
        cp target/dependency-check-report.html reports
    
    - uses: actions/upload-artifact@v4
      with:
        name: Reports
        path: reports      
        